# Generated by Django 5.1.3 on 2024-12-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_movie_duration_movie_genre_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
